spring:
  application:
    name: template-server
  
  datasource:
    # url: jdbc:mariadb://localhost:3306/template_db
    # username: root
    # password: Dltkdgjs!23
    # driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://template-db-1.cviwkua62ssd.ap-northeast-2.rds.amazonaws.com/template_db
    username: admin
    password: Tkdlem!23
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.MariaDBDialect 

# Swagger UI 설정 추가
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 설정
  api-docs:
    path: /api-docs  # API 문서 경로 설정 